### Vectorización de texto y modelo de clasificación Naïve Bayes con el dataset 20 newsgroups

In [30]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.metrics import f1_score

# 20newsgroups por ser un dataset clásico de NLP ya viene incluido y formateado
# en sklearn
from sklearn.datasets import fetch_20newsgroups
import numpy as np

import random

## Carga de datos

In [3]:
# cargamos los datos (ya separados de forma predeterminada en train y test)
newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'))

## Vectorización

In [4]:
# instanciamos un vectorizador
# ver diferentes parámetros de instanciación en la documentación de sklearn
tfidfvect = TfidfVectorizer()

In [5]:
# en el atributo `data` accedemos al texto
newsgroups_train.data[0]

'I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.'

In [6]:
# con la interfaz habitual de sklearn podemos fitear el vectorizador
# (obtener el vocabulario y calcular el vector IDF)
# y transformar directamente los datos
X_train = tfidfvect.fit_transform(newsgroups_train.data)
# `X_train` la podemos denominar como la matriz documento-término

In [7]:
# recordar que las vectorizaciones por conteos son esparsas
# por ello sklearn convenientemente devuelve los vectores de documentos
# como matrices esparsas
print(type(X_train))
print(f'shape: {X_train.shape}')
print(f'cantidad de documentos: {X_train.shape[0]}')
print(f'tamaño del vocabulario (dimensionalidad de los vectores): {X_train.shape[1]}')

<class 'scipy.sparse._csr.csr_matrix'>
shape: (11314, 101631)
cantidad de documentos: 11314
tamaño del vocabulario (dimensionalidad de los vectores): 101631


In [9]:
# una vez fiteado el vectorizador, podemos acceder a atributos como el vocabulario
# aprendido. Es un diccionario que va de términos a índices.
# El índice es la posición en el vector de documento.
tfidfvect.vocabulary_['car']

25775

In [13]:
# Borrar
fer = X_train[:, 25775]
newsgroups_train.data[0]

'I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.'

In [14]:
# es muy útil tener el diccionario opuesto que va de índices a términos
idx2word = {v: k for k, v in tfidfvect.vocabulary_.items()}

In [21]:
# en `y_train` guardamos los targets que son enteros
y_train = newsgroups_train.target
y_train[:10]

array([ 7,  4,  4,  1, 14, 16, 13,  3,  2,  4])

In [22]:
# hay 20 clases correspondientes a los 20 grupos de noticias
print(f'clases {np.unique(newsgroups_test.target)}')
newsgroups_test.target_names

clases [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

## Similaridad de documentos

In [23]:
# Veamos similaridad de documentos. Tomemos algún documento
idx = 4811
print(newsgroups_train.data[idx])

THE WHITE HOUSE

                  Office of the Press Secretary
                   (Pittsburgh, Pennslyvania)
______________________________________________________________
For Immediate Release                         April 17, 1993     

             
                  RADIO ADDRESS TO THE NATION 
                        BY THE PRESIDENT
             
                Pittsburgh International Airport
                    Pittsburgh, Pennsylvania
             
             
10:06 A.M. EDT
             
             
             THE PRESIDENT:  Good morning.  My voice is coming to
you this morning through the facilities of the oldest radio
station in America, KDKA in Pittsburgh.  I'm visiting the city to
meet personally with citizens here to discuss my plans for jobs,
health care and the economy.  But I wanted first to do my weekly
broadcast with the American people. 
             
             I'm told this station first broadcast in 1920 when
it reported that year's presidential elec

In [24]:
# midamos la similaridad coseno con todos los documentos de train
cossim = cosine_similarity(X_train[idx], X_train)[0]

In [25]:
# podemos ver los valores de similaridad ordenados de mayor a menos
np.sort(cossim)[::-1]

array([1.        , 0.70930477, 0.67474953, ..., 0.        , 0.        ,
       0.        ])

In [26]:
# y a qué documentos corresponden
np.argsort(cossim)[::-1]

array([ 4811,  6635,  4253, ...,  1534, 10055,  4750])

In [19]:
# los 5 documentos más similares:
mostsim = np.argsort(cossim)[::-1][1:6]

In [27]:
# el documento original pertenece a la clase:
newsgroups_train.target_names[y_train[idx]]

'talk.politics.misc'

In [42]:
# y los 5 más similares son de las clases:
for i in mostsim:
    print(newsgroups_train.target_names[y_train[i]])

talk.politics.misc
talk.politics.misc
talk.politics.misc
talk.politics.misc
talk.politics.misc


### Modelo de clasificación Naïve Bayes

In [28]:
# es muy fácil instanciar un modelo de clasificación Naïve Bayes y entrenarlo con sklearn
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [15]:
# con nuestro vectorizador ya fiteado en train, vectorizamos los textos
# del conjunto de test
X_test = tfidfvect.transform(newsgroups_test.data)
y_test = newsgroups_test.target
y_pred = clf.predict(X_test)

In [ ]:
# el F1-score es una metrica adecuada para reportar desempeño de modelos de claificación
# es robusta al desbalance de clases. El promediado 'macro' es el promedio de los
# F1-score de cada clase. El promedio 'micro' es equivalente a la accuracy que no
# es una buena métrica cuando los datasets son desbalanceados
f1_score(y_test, y_pred, average='macro')

0.5854345727938506

### Consigna del desafío 1

**1**. Vectorizar documentos. Tomar 5 documentos al azar y medir similaridad con el resto de los documentos.
Estudiar los 5 documentos más similares de cada uno analizar si tiene sentido
la similaridad según el contenido del texto y la etiqueta de clasificación.



In [127]:
len(newsgroups_train.data)
idxs = [random.randint(0, len(newsgroups_train.data) - 1) for i in range(5)]
print(idxs)
docs = [newsgroups_train.data[idx] for idx in idxs]
Xs_train = X_train[idxs]
Ys_train = y_train[idxs]

for i in range(len(Ys_train)):
    print(newsgroups_train.target_names[Ys_train[i]])

[4536, 1664, 2015, 11008, 11136]
alt.atheism
comp.graphics
rec.sport.baseball
sci.crypt
talk.politics.misc


In [147]:
# print(idxs)
# Medimos similitud con similitud coseno
cossim = cosine_similarity(Xs_train, X_train)

target_list = list()
result_idxs = np.zeros(shape=(5,5), dtype=int)
for i, element in enumerate(cossim):
    print("\n\nDocumento: ", i, "IDX: ", idxs[i], " Target: ", newsgroups_train.target_names[Ys_train[i]])
    result_idxs[i] = np.argsort(element)[::-1][1:6]
    
    target_list = list()
    print("Target primeros 5 documentos con mas similitud:")
    for sort_idx in result_idxs[i]:
        target_list.append(newsgroups_train.target_names[y_train[sort_idx]])
    print(target_list)
    print("IDX primeros 5 documentos con mas similitud:")
    print(result_idxs[i])
    
    print(np.sort(element)[::-1][1:6])

    # print(element)



Documento:  0 IDX:  4536  Target:  alt.atheism
Target primeros 5 documentos con mas similitud:
['alt.atheism', 'alt.atheism', 'talk.religion.misc', 'alt.atheism', 'alt.atheism']
IDX primeros 5 documentos con mas similitud:
[  656  8725 10613  4355 10836]
[0.44553524 0.3457184  0.270261   0.26283041 0.2620463 ]


Documento:  1 IDX:  1664  Target:  comp.graphics
Target primeros 5 documentos con mas similitud:
['comp.graphics', 'comp.graphics', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.graphics']
IDX primeros 5 documentos con mas similitud:
[4650 9827 1041 1579 6036]
[0.21709854 0.21166089 0.20752024 0.19765279 0.17837795]


Documento:  2 IDX:  2015  Target:  rec.sport.baseball
Target primeros 5 documentos con mas similitud:
['rec.sport.baseball', 'rec.sport.baseball', 'rec.sport.baseball', 'rec.sport.baseball', 'rec.sport.baseball']
IDX primeros 5 documentos con mas similitud:
[8717 9411 2207 7173 1651]
[0.13976603 0.13461581 0.12683939 0.11700676 0.10824562]


Documento:  3 ID

In [148]:
result_idxs

array([[  656,  8725, 10613,  4355, 10836],
       [ 4650,  9827,  1041,  1579,  6036],
       [ 8717,  9411,  2207,  7173,  1651],
       [ 4231, 11210,  6243,  9365,  5898],
       [ 9775,  4148,  1303,  1799,  8979]])

In [157]:
# Documento 1

print("DOCUMENTO 1 - TIPO: ", newsgroups_train.target_names[y_train[idxs[2]]])
print(newsgroups_train.data[idxs[2]])
print("\n---------------------------\n")
print(newsgroups_train.data[result_idxs[2,0]])

DOCUMENTO 1 - TIPO:  rec.sport.baseball
And then cs1442aq@news.uta.edu (cs1442aq) quoth:

That's too bad.  I really had hoped Nolan could end his career with a great
year.  I suppose there is still hope.


---------------------------


Depends on what you mean by "for a living".  1974 was the year he led the
league in pinch-hit at bats with 50, but he'd been getting a lot of PH ABs
earlier than that, and was never a full-time player.  20-35 PH ABs early in
his career, 15-20 a year just before going to the Dodgers, and 30-50 in the
peak years.

We're talking about a guy with a 20-year career as an outfielder, a .300+
career batting average, and 1130 or so career hits.  




**2**. Entrenar modelos de clasificación Naïve Bayes para maximizar el desempeño de clasificación
(f1-score macro) en el conjunto de datos de test. Considerar cambiar parámteros
de instanciación del vectorizador y los modelos y probar modelos de Naïve Bayes Multinomial
y ComplementNB.




Teniendo en cuenta que los textos están en Inglés, iniciamos el vectorizador utilizando el parametro stop_words='english'. De esta forma las palabras que estan en la lista no son tomadas en cuenta al momento de generar el vocabulario para vectorizar. 
A su vez, el atributo smooth_df se setea False de forma de eliminar ese documento (el cual tiene todo el vocabulario) de más que la libreria agrega a los efectos de evitar la división por cero.

In [390]:
tfidfvect2 = TfidfVectorizer(stop_words='english', smooth_idf=True)#, max_df=0.1)
X2_train = tfidfvect2.fit_transform(newsgroups_train.data)
y2_train = newsgroups_train.target
print(X_train.shape)
print(X2_train.shape)
print(y2_train.shape)

(11314, 101631)
(11314, 101322)
(11314,)


In [391]:
nb_cl = MultinomialNB(alpha=.01)
nb_cl.fit(X2_train, y2_train)
cm_cl = ComplementNB(alpha=.18)
cm_cl.fit(X2_train, y2_train)

ComplementNB(alpha=0.18)

In [392]:
X2_test = tfidfvect2.transform(newsgroups_test.data)
y2_test = newsgroups_test.target
print(X2_test.shape)
print(y2_test.shape)
y2_pred_nb = nb_cl.predict(X2_test)
y2_pred_cm = cm_cl.predict(X2_test)

(7532, 101322)
(7532,)


In [393]:
print("F1-score NB: ", f1_score(y2_test, y2_pred_nb, average='macro'))
print("F1-score CM: ", f1_score(y2_test, y2_pred_cm, average='macro'))

F1-score NB:  0.6844389919212164
F1-score CM:  0.6972162188083315



**3**. Transponer la matriz documento-término. De esa manera se obtiene una matriz
término-documento que puede ser interpretada como una colección de vectorización de palabras.
Estudiar ahora similaridad entre palabras tomando 5 palabras y estudiando sus 5 más similares. **La elección de palabras no debe ser al azar para evitar la aparición de términos poco interpretables, elegirlas "manualmente"**.

In [ ]:
0.6738107105714473
6420742151464579
0.6482017249372932
0.6467991505900852